// <auto-generated />
using System;
using App_Data.DbContextt;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_Data.Migrations
{
    [DbContext(typeof(BazaizaiContext))]
    [Migration("20230915173121_test4")]
    partial class test4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("App_Data.Models.Anh", b =>
                {
                    b.Property<Guid>("IDAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDAnh");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("Anh");
                });

            modelBuilder.Entity("App_Data.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("IDChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDChatLieu");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("App_Data.Models.ChucVu", b =>
                {
                    b.Property<Guid>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdChucVu");

                    b.ToTable("chucVus");
                });

            modelBuilder.Entity("App_Data.Models.GioHang", b =>
                {
                    b.Property<Guid>("IdNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("NguoiDungIdNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IdNguoiDung");

                    b.HasIndex("NguoiDungIdNguoiDung");

                    b.ToTable("gioHangs");
                });

            modelBuilder.Entity("App_Data.Models.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("GiaGoc")
                        .HasColumnType("float");

                    b.Property<Guid?>("IDNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDSanPhamCT")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IDNguoiDung");

                    b.HasIndex("IDSanPhamCT");

                    b.ToTable("gioHangChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdThongTinGH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("NgayShip")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("DateTime");

                    b.Property<double?>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double?>("TienShip")
                        .HasColumnType("float");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdThongTinGH");

                    b.HasIndex("IdVoucher");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("App_Data.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiaGoc")
                        .HasColumnType("float");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.KhuyenMai", b =>
                {
                    b.Property<Guid>("IDKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("LoaiHinhKM")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MucGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("PhamVi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IDKhuyenMai");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("App_Data.Models.KhuyenMaiChiTiet", b =>
                {
                    b.Property<Guid>("IDKhuyenMaiChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("IDKhuyenMai")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKhuyenMai");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSanPhamChiTiet");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IDKhuyenMaiChiTiet");

                    b.HasIndex("IDKhuyenMai");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("KhuyenMaiChiTiet", (string)null);
                });

            modelBuilder.Entity("App_Data.Models.KichCo", b =>
                {
                    b.Property<Guid>("IDKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoKichCo")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IDKichCo");

                    b.ToTable("kichCos");
                });

            modelBuilder.Entity("App_Data.Models.KieuDeGiay", b =>
                {
                    b.Property<Guid>("IdKieuDeGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaKieuDeGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenKieuDeGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("IdKieuDeGiay");

                    b.ToTable("kieuDeGiays");
                });

            modelBuilder.Entity("App_Data.Models.LoaiGiay", b =>
                {
                    b.Property<Guid>("IdLoaiGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaLoaiGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenLoaiGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdLoaiGiay");

                    b.ToTable("LoaiGiays");
                });

            modelBuilder.Entity("App_Data.Models.MauSac", b =>
                {
                    b.Property<Guid>("IDMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDMauSac");

                    b.ToTable("mauSacs");
                });

            modelBuilder.Entity("App_Data.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("IdNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<Guid>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("App_Data.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("IDPhuongThucThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDPhuongThucThanhToan");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("App_Data.Models.PhuongThucThanhToanChiTiet", b =>
                {
                    b.Property<Guid>("IDPhuongThucThanhToanChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("SoTien")
                        .HasColumnType("float");

                    b.HasKey("IDPhuongThucThanhToanChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdThanhToan");

                    b.ToTable("phuongThucThanhToanChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("IdSanPham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("App_Data.Models.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IDChiTietSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(250)");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKieuDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLoaiGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdXuatXu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("Nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiSale")
                        .HasColumnType("int");

                    b.HasKey("IDChiTietSp");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdKichCo");

                    b.HasIndex("IdKieuDeGiay");

                    b.HasIndex("IdLoaiGiay");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdThuongHieu");

                    b.HasIndex("IdXuatXu");

                    b.ToTable("sanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("IDSanPhamYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("IDNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IDSanPhamYeuThich");

                    b.HasIndex("IDNguoiDung");

                    b.ToTable("sanPhamYeuThiches");
                });

            modelBuilder.Entity("App_Data.Models.ThongTinGiaoHang", b =>
                {
                    b.Property<Guid>("IdThongTinGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("IdNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdThongTinGH");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("thongTinGiaoHangs");
                });

            modelBuilder.Entity("App_Data.Models.ThuongHieu", b =>
                {
                    b.Property<Guid>("IDThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IDThuongHieu");

                    b.ToTable("thuongHieus");
                });

            modelBuilder.Entity("App_Data.Models.Voucher", b =>
                {
                    b.Property<Guid>("IdVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DieuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LoaiHinhUuDai")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MucUuDai")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdVoucher");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("App_Data.Models.VoucherNguoiDung", b =>
                {
                    b.Property<Guid>("IdVouCherNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVouCher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdVouCherNguoiDung");

                    b.HasIndex("IdNguoiDung");

                    b.HasIndex("IdVouCher");

                    b.ToTable("voucherNguoiDungs");
                });

            modelBuilder.Entity("App_Data.Models.XuatXu", b =>
                {
                    b.Property<Guid>("IDXuatXu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDXuatXu");

                    b.ToTable("xuatXus");
                });

            modelBuilder.Entity("ChucVuNguoiDung", b =>
                {
                    b.Property<Guid>("ChucVuIdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguoiDungsIdNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChucVuIdChucVu", "NguoiDungsIdNguoiDung");

                    b.HasIndex("NguoiDungsIdNguoiDung");

                    b.ToTable("ChucVuNguoiDung");
                });

            modelBuilder.Entity("App_Data.Models.Anh", b =>
                {
                    b.HasOne("App_Data.Models.SanPhamChiTiet", "SanPhamChiTiets")
                        .WithMany("Anh")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.GioHang", b =>
                {
                    b.HasOne("App_Data.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungIdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("App_Data.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("App_Data.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiet")
                        .HasForeignKey("IDNguoiDung");

                    b.HasOne("App_Data.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiet")
                        .HasForeignKey("IDSanPhamCT");

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.HoaDon", b =>
                {
                    b.HasOne("App_Data.Models.ThongTinGiaoHang", "ThongTinGiaoHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdThongTinGH");

                    b.HasOne("App_Data.Models.Voucher", "Voucher")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdVoucher");

                    b.Navigation("ThongTinGiaoHang");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("App_Data.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("App_Data.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiet")
                        .HasForeignKey("IdHoaDon");

                    b.HasOne("App_Data.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiet")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.KhuyenMaiChiTiet", b =>
                {
                    b.HasOne("App_Data.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("KhuyenMaiChiTiet")
                        .HasForeignKey("IDKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("KhuyenMaiChiTiet")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.PhuongThucThanhToanChiTiet", b =>
                {
                    b.HasOne("App_Data.Models.HoaDon", "HoaDons")
                        .WithMany("PhuongThucThanhToanChiTiet")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data.Models.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("PhuongThucThanhToanChiTiets")
                        .HasForeignKey("IdThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDons");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("App_Data.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("App_Data.Models.ChatLieu", "ChatLieu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdChatLieu");

                    b.HasOne("App_Data.Models.KichCo", "KichCo")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdKichCo");

                    b.HasOne("App_Data.Models.KieuDeGiay", "KieuDeGiay")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdKieuDeGiay");

                    b.HasOne("App_Data.Models.LoaiGiay", "LoaiGiay")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdLoaiGiay");

                    b.HasOne("App_Data.Models.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMauSac");

                    b.HasOne("App_Data.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSanPham");

                    b.HasOne("App_Data.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdThuongHieu");

                    b.HasOne("App_Data.Models.XuatXu", "XuatXu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdXuatXu");

                    b.Navigation("ChatLieu");

                    b.Navigation("KichCo");

                    b.Navigation("KieuDeGiay");

                    b.Navigation("LoaiGiay");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("ThuongHieu");

                    b.Navigation("XuatXu");
                });

            modelBuilder.Entity("App_Data.Models.SanPhamYeuThich", b =>
                {
                    b.HasOne("App_Data.Models.NguoiDung", "NguoiDung")
                        .WithMany("SanPhamYeuThich")
                        .HasForeignKey("IDNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("App_Data.Models.ThongTinGiaoHang", b =>
                {
                    b.HasOne("App_Data.Models.NguoiDung", "NguoiDungs")
                        .WithMany("ThongTinGiaoHangs")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("App_Data.Models.VoucherNguoiDung", b =>
                {
                    b.HasOne("App_Data.Models.NguoiDung", "NguoiDungs")
                        .WithMany("VoucherNguoiDungs")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data.Models.Voucher", "Vouchers")
                        .WithMany("VoucherNguoiDungs")
                        .HasForeignKey("IdVouCher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDungs");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("ChucVuNguoiDung", b =>
                {
                    b.HasOne("App_Data.Models.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("ChucVuIdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Data.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungsIdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App_Data.Models.ChatLieu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiet");

                    b.Navigation("PhuongThucThanhToanChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.KhuyenMai", b =>
                {
                    b.Navigation("KhuyenMaiChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.KieuDeGiay", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.LoaiGiay", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.NguoiDung", b =>
                {
                    b.Navigation("SanPhamYeuThich");

                    b.Navigation("ThongTinGiaoHangs");

                    b.Navigation("VoucherNguoiDungs");
                });

            modelBuilder.Entity("App_Data.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("PhuongThucThanhToanChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("Anh");

                    b.Navigation("GioHangChiTiet");

                    b.Navigation("HoaDonChiTiet");

                    b.Navigation("KhuyenMaiChiTiet");
                });

            modelBuilder.Entity("App_Data.Models.ThongTinGiaoHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("App_Data.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("App_Data.Models.Voucher", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("VoucherNguoiDungs");
                });

            modelBuilder.Entity("App_Data.Models.XuatXu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
